# Generated by Django 5.1.15 on 2026-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('total_trip_duration_hours', models.FloatField(default=0.0)),
                ('total_days', models.IntegerField(default=1)),
                ('carrier_name', models.CharField(default='Spotter Logistics LLC', max_length=255)),
                ('driver_name', models.CharField(default='Kavankumar', max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('remaining_cycle_hours', models.FloatField(default=70.0)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Trip Plan Record',
                'verbose_name_plural': 'Trip Plan Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
